In [1]:
text_human = u"It often happens that while working on one project, you need to use another project from within it. Perhaps it’s a library that a third party developed or that you’re developing separately and using in multiple parent projects. A common issue arises in these scenarios: you want to be able to treat the two projects as separate yet still be able to use one from within the other."
text_gpt2 = u"Good news for The Logan Society members [kiss_off/Stephen] and their allies. There's a new news article cited above that says we can rest assured as of now that the project is not dead, but will instead be put on permanent hiatus for the foreseeable future. There's no official reason for the decision, though we can hazard some guesses which do have Hexpoint infringements tolement, and multiple individuals have already taken to Discord to say it isn't a good idea. Keep in mind that this article is authored by the person who actually contacted Hexpoint directly, and he contradicted the article's claims up and down in more subtle ways."
lorem_ipsum = u"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
nyt = u'European Union policymakers agreed on Friday to a sweeping new law to regulate artificial intelligence, one of the world’s first comprehensive attempts to limit the use of a rapidly evolving technology that has wide-ranging societal and economic implications. The law, called the A.I. Act, sets a new global benchmark for countries seeking to harness the potential benefits of the technology, while trying to protect against its possible risks, like automating jobs, spreading misinformation online and endangering national security. The law still needs to go through a few final steps for approval, but the political agreement means its key outlines have been set.'
emma = u'Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her. She was the youngest of the two daughters of a most affectionate, indulgent father; and had, in consequence of her sister’s marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection. Sixteen years had Miss Taylor been in Mr. Woodhouse’s family, less as a governess than a friend, very fond of both daughters, but particularly of Emma. Between them it was more the intimacy of sisters. Even before Miss Taylor had ceased to hold the nominal office of governess, the mildness of her temper had hardly allowed her to impose any restraint; and the shadow of authority being now long passed away, they had been living together as friend and friend very mutually attached, and Emma doing just what she liked; highly esteeming Miss Taylor’s judgment, but directed chiefly by her own.'
human_h3 = u"""Basically there are many categories of " Best Seller " . Replace " Best Seller " by something like " Oscars " and every " best seller " book is basically an " oscar - winning " book . May not have won the " Best film " , but even if you won the best director or best script , you 're still an " oscar - winning " film . Same thing for best sellers . Also , IIRC the rankings change every week or something like that . Some you might not be best seller one week , but you may be the next week . I guess even if you do n't stay there for long , you still achieved the status . Hence , # 1 best seller ."""
machine_h3 = u"""There are many different best seller lists that are published by various organizations, and the New York Times is just one of them. The New York Times best seller list is a weekly list that ranks the best-selling books in the United States based on sales data from a number of different retailers. The list is published in the New York Times newspaper and is widely considered to be one of the most influential best seller lists in the book industry.  It's important to note that the New York Times best seller list is not the only best seller list out there, and there are many other lists that rank the top-selling books in different categories or in different countries. So it's possible that a book could be a best seller on one list but not on another. Additionally, the term "best seller" is often used more broadly to refer to any book that is selling well, regardless of whether it is on a specific best seller list or not. So it's possible that you may hear about a book being a "best seller" even if it is not specifically ranked as a number one best seller on the New York Times list or any other list."""

In [2]:
from detectgpt.detector_detectgpt import DetectorDetectGPT
from gpt2outputdataset.detector_radford import DetectorRadford

In [3]:

detector_detectgpt = DetectorRadford()
#detector_radford = DetectorRadford()

Using cache dir ./.cache
Loading BASE model EleutherAI/pythia-70m...
Loading mask filling model t5-small...
MOVING BASE MODEL TO GPU...DONE (2.01s)
Initialized


In [4]:
# detector_detectgpt.predict_proba_machine([machine_h3])

In [5]:
# detector_detectgpt.predict_proba_machine([machine_h3,machine_h3,machine_h3])

In [6]:
# detector_detectgpt.predict_proba_machine([machine_h3,machine_h3,machine_h3])

In [7]:
# detector_detectgpt.predict_proba([machine_h3])

In [8]:
# detector_detectgpt.predict_proba(['<<<mask>>>'])

In [9]:
# detector_radford = DetectorRadford()

In [10]:
# detector_radford.predict_proba([machine_h3])

In [11]:
import shap
import transformers
import numpy as np

In [12]:
tokenizer = transformers.DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
) # example from https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/text.html

In [13]:
masker = shap.maskers.Text(tokenizer, mask_token=detector_detectgpt.get_mask_token())
explainer = shap.Explainer(detector_detectgpt.predict_proba_machine, tokenizer=tokenizer, masker=masker)

In [14]:
text = '<|endoftext|>So it\'s possible that you may hear about a book being a "best seller" even if it is not specifically ranked as a number one best seller on the New York Times list or any other list.'

In [15]:
detector_detectgpt.predict_proba_machine([human_h3, machine_h3])

MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)


Computing log likelihoods: 100%|██████████| 2/2 [00:00<00:00, 12.39it/s]


[[0 1]
 [1 0]]


[False, True]

In [16]:
detector_detectgpt.predict_proba_(["<|endoftext|>","<|endoftext|>","<|endoftext|>","<|endoftext|>"])

MOVING MASK MODEL TO GPU...DONE (0.11s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext

Applying perturbations: 100%|██████████| 1/1 [00:10<00:00, 10.65s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)


Computing log likelihoods: 100%|██████████| 4/4 [00:00<00:00, 18.02it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>


array([-0.84618759, -0.83623205, -1.22767736, -1.77722854])

In [17]:
detector_detectgpt.predict_proba_machine(["<|endoftext|>","<|endoftext|>","<|endoftext|>","<|endoftext|>"])

MOVING MASK MODEL TO GPU...DONE (0.13s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext

Applying perturbations: 100%|██████████| 1/1 [00:10<00:00, 10.81s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)


Computing log likelihoods: 100%|██████████| 4/4 [00:00<00:00, 19.38it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>
[[1 0]
 [1 0]
 [1 0]
 [1 0]]


[True, True, True, True]

In [18]:
text = ['<|endoftext|>','Test 1234 Loris','Test 1234 <|endoftext|>', '<|endoftext|>Loris','<|endoftext|>Loris', '<|endoftext|>', 'Test <|endoftext|>Loris',
 '<|endoftext|>1234 Loris', 'Test <|endoftext|>',
 '<|endoftext|>1234 <|endoftext|>','<|endoftext|>123 <|endoftext|>Loris', '<|endoftext|>4 Loris',
 'Test 123 <|endoftext|>Loris', 'Test <|endoftext|>4 Loris', '<|endoftext|>',
 'Test <|endoftext|>']
out = [0,0,0,0,0, 0, 0, 0, 0, 0,0, 0, 0, 0, 0, 0,]

In [19]:
# out2 = detector_detectgpt.predict_proba_machine(text)

In [20]:
# (out == out2).all() and len(out) == len(out2)

In [21]:
np.random.random()

0.8434770492184945

In [ ]:
detector_detectgpt.predict_proba_machine(["This", "is", "a", "test", "<|endoftext|>"])

In [22]:
# TODO zero rows shap_values = explainer(["Test 1234 Loris"]) TC test add up to 1
shap_values = explainer([human_h3])

MOVING MASK MODEL TO GPU...DONE (0.14s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']


Applying perturbations: 100%|██████████| 1/1 [00:11<00:00, 11.15s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00, 15.96it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>
[[0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00, 12.01it/s]


[[0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  2.12it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)


Computing log likelihoods: 100%|██████████| 2/2 [00:00<00:00, 13.53it/s]


[[0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.18s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.79s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)


Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.76it/s]


[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.02it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]


  0%|          | 0/498 [00:00<?, ?it/s]

MOVING MASK MODEL TO GPU...DONE (0.15s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.15s/it]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.16it/s]


[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.79s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.64it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>May not have won the " Best film " , <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>but even if you won the best director or best script , <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 11.19it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.87it/s]


[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.15s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.25it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.21s/it]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.11it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.15it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.39it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.57it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.32it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.85it/s]


[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.78s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.45it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.27it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.87s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.36it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.68it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.20it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.04it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.94it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.25it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.81it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.49it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.06it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.75it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.84it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:03<00:00,  3.82s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.77it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.24s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.28it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.89s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.11it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.27it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.88it/s]


[[1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.94s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.53it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>May not have won the " Best film " , <|endoftext|>best script <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>May not have won the " Best film " , <|endoftext|>, <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.84s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.65it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<|endoftext|>May not <|endoftext|>the " Best film " , but even if you won the best director <extra_id_0> script , <|endoftext|>', '<|endoftext|>May not <|endoftext|>the " Best film " , but even if you won the <extra_id_0> or best script , <|endoftext|>', '<|endoftext|>May not <|endoftext|>the " Best film " , but even if you won the best <extra_id_0> best script , <|endoftext|>', '<|endoftext|>have won <extra_id_0> Best film " , but even if you won the best director or best script , <|endoftext|>', '<|endoftext|>have won the " Best film " , but even if <extra_id_0> the best director or best script , <|endoftext|>', '<|endoftext|>have won the " Best <extra_id_0> , but even if you won the best director or best script , <|endoftext|>', '<|endoftext|>May not have won the " Best <extra_id_0> , but <|endoftext|>the best director or best script , <|endoftext|>Also , IIRC the rankings change every week or something like <extra_id_1> Some you might not be best seller <extra_id_2> , but you


Applying perturbations: 100%|██████████| 1/1 [00:03<00:00,  3.27s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.37it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.98it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.15s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:03<00:00,  3.03s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.13it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.18s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.95s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.07it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.58it/s]


[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.18it/s]


[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.97it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.88it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.87it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.96it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.40it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.83it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.71it/s]


[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.79it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.58it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.61it/s]


[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.96it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.15s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.21it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.52it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.67it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.04it/s]


[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.95it/s]


[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.75it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.04it/s]


[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.82s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.27it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>May not have won the " Best film " , <|endoftext|>best <|endoftext|>, <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>May not have won the " Best film " , <|endoftext|>script , <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.48it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.18it/s]


[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.39it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.80it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.71it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.55it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.79it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.74it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.15s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.88s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.08it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.11it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.35it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.88it/s]


[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.31it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.80it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.43it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.63it/s]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.08it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.50it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.02it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.10it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.30it/s]


[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.71it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.87it/s]


[[1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.95it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.18s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.32it/s]


[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.15it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.60it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.02s/it]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.47it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.10it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.97it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.24s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.49it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.25it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.28it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.24it/s]


[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.18s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.17it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.73it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.81s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 12.91it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.11it/s]


MOVING BASE MODEL TO GPU...DONE (0.16s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.09it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.83s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.00it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.21it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 4/4 [00:00<00:00, 12.91it/s]


[[0 1]
 [0 1]
 [0 1]
 [0 1]]


PartitionExplainer explainer: 2it [02:52, 172.27s/it]              


In [23]:
shap.plots.text(shap_values)

In [33]:
shap_values = explainer([machine_h3])

MOVING MASK MODEL TO GPU...DONE (0.20s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']
epr ['<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>']


Applying perturbations: 100%|██████████| 1/1 [00:11<00:00, 11.17s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00, 17.20it/s]


[[0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00, 10.44it/s]


[[1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)


Computing log likelihoods: 100%|██████████| 2/2 [00:00<00:00, 12.09it/s]


[[1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.11s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.70s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)


Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.34it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  2.17it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)


Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.79it/s]


[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]


  0%|          | 0/498 [00:00<?, ?it/s]

MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<|endoftext|>So it\'s possible that you may hear about <extra_id_0> being a "best seller" even if it is not specifically ranked as a number one best seller on the New <extra_id_1> list or any other list.', '<|endoftext|>So it\'s possible that you may hear about a book being a "best <extra_id_0> if it is not <extra_id_1> as a number one best seller on the New York Times list or any other list.', '<|endoftext|>So it\'s possible that you may hear about a book being <extra_id_0> seller" even if it is not specifically <extra_id_1> a number one best seller on the New York Times list or any other list.', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<extra_id_0> <|endoftext|>', '<|endoftext|>The New York Times best seller list is a <extra_id_0> that ranks the best- <|endoftext|>', '<|endoftext|>The New York Times best seller list <extra_id_0> weekly list that ranks the best- <|endoftext|>', '<|endoftext|>The New York Times best seller list is a weekly list that <extra_id_


Applying perturbations: 100%|██████████| 1/1 [00:10<00:00, 10.83s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.99it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>
[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.78s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.53it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>The list is published in the New York Times newspaper and <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.76s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.33it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>could be a best seller on one list but not on another. <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.67s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.15it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book <|endoftext|>not on another. <|endoftext|>
[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.78s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.25it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>is widely considered to be one of the <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>most influential best seller lists in the book industry. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>not the only best seller list out there, <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.82s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.11it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a specific best seller list <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>or not. <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.87s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.96it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>selling books in the United States based on <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>sales data from a number of different retailers. <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.83s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.38it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>the New York Times list or any other list.
[[1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.73s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.63it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it <|endoftext|>or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>is on a specific best seller list or not. <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.80s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.46it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>selling books in the United States based on sales data from a <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>selling books in the United States based on <|endoftext|>number of different retailers. <|endoftext|>
[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.78s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.84it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a specific best seller list or <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a specific best seller list <|endoftext|>not. <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.79s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.79it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book <|endoftext|>seller on one list but <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>the New York Times best seller list is <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.81s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.51it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>seller" even if it is not specifically <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>ranked as a number one best seller on <|endoftext|>
[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.85s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.81it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>selling books in the <|endoftext|>sales data from a number of different retailers. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>United States based on sales data from a number of different retailers. <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.28it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.87s/it]


MOVING BASE MODEL TO GPU...DONE (0.15s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 11.40it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>is widely considered to be one of the most influential best seller <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.16s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:03<00:00,  3.53s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.81it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.89s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.83it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  3.04it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.81it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.80s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.86it/s]


[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.84s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.16it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a specific <|endoftext|>or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it <|endoftext|>best seller list or not. <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.17s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.91s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.83it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be <|endoftext|>not on another. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book <|endoftext|>a best <|endoftext|>not on another. <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.82s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.13it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>seller" even if <|endoftext|>ranked as a number one best seller on <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>it is not specifically ranked as a number one best seller on <|endoftext|>
[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.88s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.83it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>the New York Times <|endoftext|>not the only best seller list out there, <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>best seller list is not the only best seller list out there, <|endoftext|>
[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.82s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.91it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.69s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.03it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>seller" even if it is not specifically ranked as a number <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>seller" even if it is not specifically <|endoftext|>one best seller on <|endoftext|>
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.84s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.70it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of <|endoftext|>is on a specific best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>whether it is on a specific best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best <|endoftext|>but <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.91s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.07it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's <|endoftext|>the New York Times best seller list is <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>important to note that the New York Times best seller list is <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.74it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.18it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.76it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  3.85it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.23it/s]


[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.10s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations:   0%|          | 0/1 [00:00<?, ?it/s]

epr ['<|endoftext|>selling <extra_id_0> States based on sales data from a number of different retailers. <|endoftext|>', '<|endoftext|>selling books <|endoftext|>United States based on sales data from a <extra_id_0> different retailers. <|endoftext|>', '<|endoftext|>selling books <|endoftext|>United States based <extra_id_0> data from a number of different retailers. <|endoftext|>', '<|endoftext|>in the United States based <extra_id_0> data from a number of different retailers. <|endoftext|>', '<|endoftext|>in the United States based on sales data from a <extra_id_0> different retailers. <|endoftext|>', '<|endoftext|>in the United States <extra_id_0> sales data from a number of different retailers. <|endoftext|>', '<|endoftext|>selling books in the United States <|endoftext|>sales data from <extra_id_0> of different retailers. <|endoftext|>', '<|endoftext|>selling books <extra_id_0> United States <|endoftext|>sales data from a number of different retailers. <|endoftext|>', '<|endoftext


Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.98s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 18.19it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that the New York Times <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that <|endoftext|>best seller list is <|endoftext|>
[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.79s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.13it/s]


[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.84it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.74it/s]


[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.75it/s]


[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.44it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.81it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  3.06it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.44it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.87s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.63it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to <|endoftext|>the New York Times best seller list is <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's <|endoftext|>note that the New York Times best seller list is <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>widely considered to be one of the most influential best seller lists in the book industry. <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.73s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.98it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.05it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  8.53it/s]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.81it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.10s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.81s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.39it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that the New <|endoftext|>best seller list is <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that <|endoftext|>York Times best seller list is <|endoftext|>
[[1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.76s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.58it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best seller on <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best <|endoftext|>one list <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could <|endoftext|>seller on one list but <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book <|endoftext|>be <|endoftext|>seller on one list but <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.76s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.20it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.71s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.35it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could <|endoftext|>a best <|endoftext|>not on another. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book <|endoftext|>be a best <|endoftext|>not on another. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether <|endoftext|>is on a specific best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of <|endoftext|>it is on a specific best seller list or not. <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  5.30it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.63it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.08s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.72s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.45it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a <|endoftext|>not on another. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be <|endoftext|>best <|endoftext|>not on another. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless <|endoftext|>whether it is on a specific best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>of whether it is on a specific best seller list or not. <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.65s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.22it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on <|endoftext|>best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it <|endoftext|>a specific best seller list or not. <|endoftext|>
[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  4.95it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.74it/s]


[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.10s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.62s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.01it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  2.49it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.85it/s]


[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.10s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.72s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.81it/s]


[[0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.66it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.19it/s]


[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  5.57it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.79it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  3.57it/s]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.73it/s]


[[1 0]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.61it/s]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.07it/s]


[[1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.15s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.73s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.16it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.83s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.79it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that the New York Times best seller <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>It's important to note that the New York Times <|endoftext|>list is <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.95it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.94it/s]


[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.95it/s]


[[0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  3.71it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.49it/s]


[[1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  3.58it/s]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.90it/s]


[[1 0]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.10s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.78s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.84it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a specific best seller <|endoftext|>or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a specific <|endoftext|>list or not. <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  8.28it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.31it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.79s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.12it/s]


[[1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  4.59it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.08it/s]


[[0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.71s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.87it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best <|endoftext|>one <|endoftext|>but <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best <|endoftext|>list but <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.71s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.25it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is <|endoftext|>a specific best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it <|endoftext|>on a specific best seller list or not. <|endoftext|>
[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  2.38it/s]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.96it/s]


[[0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.16s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  4.99it/s]


MOVING BASE MODEL TO GPU...DONE (0.09s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.69it/s]


[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.74s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.87it/s]


[[1 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.12s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.71it/s]


[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.74it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 17.03it/s]


[[0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.11s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.75s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.90it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on a <|endoftext|>best seller list or not. <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>regardless of whether it is on <|endoftext|>specific best seller list or not. <|endoftext|>
[[0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  5.68it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 16.47it/s]


[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.09s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  5.75it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.33it/s]


[[0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.10s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.85s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 15.36it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best seller <|endoftext|>but <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>So it's possible that a book could be a best <|endoftext|>on <|endoftext|>but <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.82it/s]


MOVING BASE MODEL TO GPU...DONE (0.13s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 13.39it/s]


[[1 0]
 [0 1]
 [1 0]
 [1 0]
 [0 1]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.14s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.95s/it]


MOVING BASE MODEL TO GPU...DONE (0.14s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.58it/s]


[[1 0]
 [1 0]
 [0 1]
 [1 0]
 [1 0]
 [1 0]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00, 14.96it/s]


[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]]
MOVING MASK MODEL TO GPU...DONE (0.12s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 1/1 [00:00<00:00,  4.05it/s]


MOVING BASE MODEL TO GPU...DONE (0.11s)



Computing log likelihoods: 100%|██████████| 4/4 [00:00<00:00, 15.31it/s]


[[1 0]
 [0 1]
 [0 1]
 [1 0]]


PartitionExplainer explainer: 2it [03:48, 228.79s/it]              


In [34]:
shap.plots.text(shap_values)

In [25]:
human_h3

'Basically there are many categories of " Best Seller " . Replace " Best Seller " by something like " Oscars " and every " best seller " book is basically an " oscar - winning " book . May not have won the " Best film " , but even if you won the best director or best script , you \'re still an " oscar - winning " film . Same thing for best sellers . Also , IIRC the rankings change every week or something like that . Some you might not be best seller one week , but you may be the next week . I guess even if you do n\'t stay there for long , you still achieved the status . Hence , # 1 best seller .'

In [26]:
54zthg

SyntaxError: invalid decimal literal (1675399054.py, line 1)

In [ ]:
shap.plots.text(shap_values)