In [1]:
text_human = u"It often happens that while working on one project, you need to use another project from within it. Perhaps it’s a library that a third party developed or that you’re developing separately and using in multiple parent projects. A common issue arises in these scenarios: you want to be able to treat the two projects as separate yet still be able to use one from within the other."
text_gpt2 = u"Good news for The Logan Society members [kiss_off/Stephen] and their allies. There's a new news article cited above that says we can rest assured as of now that the project is not dead, but will instead be put on permanent hiatus for the foreseeable future. There's no official reason for the decision, though we can hazard some guesses which do have Hexpoint infringements tolement, and multiple individuals have already taken to Discord to say it isn't a good idea. Keep in mind that this article is authored by the person who actually contacted Hexpoint directly, and he contradicted the article's claims up and down in more subtle ways."
lorem_ipsum = u"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
nyt = u'European Union policymakers agreed on Friday to a sweeping new law to regulate artificial intelligence, one of the world’s first comprehensive attempts to limit the use of a rapidly evolving technology that has wide-ranging societal and economic implications. The law, called the A.I. Act, sets a new global benchmark for countries seeking to harness the potential benefits of the technology, while trying to protect against its possible risks, like automating jobs, spreading misinformation online and endangering national security. The law still needs to go through a few final steps for approval, but the political agreement means its key outlines have been set.'
emma = u'Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her. She was the youngest of the two daughters of a most affectionate, indulgent father; and had, in consequence of her sister’s marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection. Sixteen years had Miss Taylor been in Mr. Woodhouse’s family, less as a governess than a friend, very fond of both daughters, but particularly of Emma. Between them it was more the intimacy of sisters. Even before Miss Taylor had ceased to hold the nominal office of governess, the mildness of her temper had hardly allowed her to impose any restraint; and the shadow of authority being now long passed away, they had been living together as friend and friend very mutually attached, and Emma doing just what she liked; highly esteeming Miss Taylor’s judgment, but directed chiefly by her own.'
human_h3 = u"""Basically there are many categories of " Best Seller " . Replace " Best Seller " by something like " Oscars " and every " best seller " book is basically an " oscar - winning " book . May not have won the " Best film " , but even if you won the best director or best script , you 're still an " oscar - winning " film . Same thing for best sellers . Also , IIRC the rankings change every week or something like that . Some you might not be best seller one week , but you may be the next week . I guess even if you do n't stay there for long , you still achieved the status . Hence , # 1 best seller ."""
machine_h3 = u"""There are many different best seller lists that are published by various organizations, and the New York Times is just one of them. The New York Times best seller list is a weekly list that ranks the best-selling books in the United States based on sales data from a number of different retailers. The list is published in the New York Times newspaper and is widely considered to be one of the most influential best seller lists in the book industry.  It's important to note that the New York Times best seller list is not the only best seller list out there, and there are many other lists that rank the top-selling books in different categories or in different countries. So it's possible that a book could be a best seller on one list but not on another. Additionally, the term "best seller" is often used more broadly to refer to any book that is selling well, regardless of whether it is on a specific best seller list or not. So it's possible that you may hear about a book being a "best seller" even if it is not specifically ranked as a number one best seller on the New York Times list or any other list."""

In [2]:
from detectgpt.detector_detectgpt import DetectorDetectGPT
from gpt2outputdataset.detector_radford import DetectorRadford

In [3]:

detector_detectgpt = DetectorDetectGPT()
#detector_radford = DetectorRadford()

Using cache dir ./.cache
Loading BASE model EleutherAI/pythia-70m...
Loading mask filling model t5-small...
MOVING BASE MODEL TO GPU...DONE (1.87s)
Initialized


In [4]:
detector_detectgpt.predict_proba_machine([machine_h3])

texts predict proba ['There are many different best seller lists that are published by various organizations, and the New York Times is just one of them. The New York Times best seller list is a weekly list that ranks the best-selling books in the United States based on sales data from a number of different retailers. The list is published in the New York Times newspaper and is widely considered to be one of the most influential best seller lists in the book industry.  It\'s important to note that the New York Times best seller list is not the only best seller list out there, and there are many other lists that rank the top-selling books in different categories or in different countries. So it\'s possible that a book could be a best seller on one list but not on another. Additionally, the term "best seller" is often used more broadly to refer to any book that is selling well, regardless of whether it is on a specific best seller list or not. So it\'s possible that you may hear about a 

Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.85s/it]


MOVING BASE MODEL TO GPU...DONE (0.09s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00,  5.05it/s]


[[1 0]]


array([1.])

In [5]:
detector_detectgpt.predict_proba_machine([machine_h3,machine_h3,machine_h3])

texts predict proba ['There are many different best seller lists that are published by various organizations, and the New York Times is just one of them. The New York Times best seller list is a weekly list that ranks the best-selling books in the United States based on sales data from a number of different retailers. The list is published in the New York Times newspaper and is widely considered to be one of the most influential best seller lists in the book industry.  It\'s important to note that the New York Times best seller list is not the only best seller list out there, and there are many other lists that rank the top-selling books in different categories or in different countries. So it\'s possible that a book could be a best seller on one list but not on another. Additionally, the term "best seller" is often used more broadly to refer to any book that is selling well, regardless of whether it is on a specific best seller list or not. So it\'s possible that you may hear about a 

Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 2/2 [00:02<00:00,  1.34s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 3/3 [00:00<00:00,  5.28it/s]


[[1 0]
 [1 0]
 [1 0]]


array([1., 1., 1.])

In [6]:
detector_detectgpt.predict_proba_machine([machine_h3,machine_h3,machine_h3])

texts predict proba ['There are many different best seller lists that are published by various organizations, and the New York Times is just one of them. The New York Times best seller list is a weekly list that ranks the best-selling books in the United States based on sales data from a number of different retailers. The list is published in the New York Times newspaper and is widely considered to be one of the most influential best seller lists in the book industry.  It\'s important to note that the New York Times best seller list is not the only best seller list out there, and there are many other lists that rank the top-selling books in different categories or in different countries. So it\'s possible that a book could be a best seller on one list but not on another. Additionally, the term "best seller" is often used more broadly to refer to any book that is selling well, regardless of whether it is on a specific best seller list or not. So it\'s possible that you may hear about a 

Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 2/2 [00:02<00:00,  1.36s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 3/3 [00:00<00:00,  4.61it/s]


[[1 0]
 [1 0]
 [1 0]]


array([1., 1., 1.])

In [7]:
detector_detectgpt.predict_proba([machine_h3])

texts predict proba ['There are many different best seller lists that are published by various organizations, and the New York Times is just one of them. The New York Times best seller list is a weekly list that ranks the best-selling books in the United States based on sales data from a number of different retailers. The list is published in the New York Times newspaper and is widely considered to be one of the most influential best seller lists in the book industry.  It\'s important to note that the New York Times best seller list is not the only best seller list out there, and there are many other lists that rank the top-selling books in different categories or in different countries. So it\'s possible that a book could be a best seller on one list but not on another. Additionally, the term "best seller" is often used more broadly to refer to any book that is selling well, regardless of whether it is on a specific best seller list or not. So it\'s possible that you may hear about a 

Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:01<00:00,  1.37s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00,  5.02it/s]


[[1 0]]


array([[1, 0]])

In [8]:
# detector_detectgpt.predict_proba(['<<<mask>>>'])

In [9]:
# detector_radford = DetectorRadford()

In [10]:
# detector_radford.predict_proba([machine_h3])

In [11]:
import shap
import transformers
import numpy as np

In [12]:
tokenizer = transformers.DistilBertTokenizerFast.from_pretrained(
    "distilbert-base-uncased"
) # example from https://shap.readthedocs.io/en/latest/example_notebooks/api_examples/plots/text.html

In [13]:
masker = shap.maskers.Text(tokenizer, mask_token=detector_detectgpt.get_mask_token())
explainer = shap.Explainer(detector_detectgpt.predict_proba_machine, tokenizer=tokenizer, masker=masker)

In [14]:
text = '<|endoftext|>So it\'s possible that you may hear about a book being a "best seller" even if it is not specifically ranked as a number one best seller on the New York Times list or any other list.'

In [15]:
detector_detectgpt.predict_proba_machine(["Test 1234 Loris"])

texts predict proba ['Test 1234 Loris']
MOVING MASK MODEL TO GPU...DONE (0.13s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.75s/it]


MOVING BASE MODEL TO GPU...DONE (0.11s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00,  6.85it/s]


Number of unique perturbed original texts: 1
Original text: Test 1234 Loris
[[0 1]]


array([0.])

In [16]:
# TODO zero rows shap_values = explainer(["Test 1234 Loris"])
shap_values = explainer(["Test 1234 Loris"])

texts predict proba ['<|endoftext|>']
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.65s/it]


MOVING BASE MODEL TO GPU...DONE (0.10s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00,  6.06it/s]


[[0 0]]
texts predict proba ['Test 1234 Loris']
MOVING MASK MODEL TO GPU...DONE (0.11s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.64s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)


Computing log likelihoods: 100%|██████████| 1/1 [00:00<00:00,  6.37it/s]


Number of unique perturbed original texts: 1
Original text: Test 1234 Loris
[[0 1]]
texts predict proba ['Test 1234 <|endoftext|>' '<|endoftext|>Loris']
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 1/1 [00:02<00:00,  2.95s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)


Computing log likelihoods: 100%|██████████| 2/2 [00:00<00:00,  6.34it/s]


Number of unique perturbed original texts: 1
Original text: Test 1234 <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>Loris
[[0 1]
 [0 1]]
texts predict proba ['<|endoftext|>Loris' '<|endoftext|>' 'Test <|endoftext|>Loris'
 '<|endoftext|>1234 Loris' 'Test <|endoftext|>'
 '<|endoftext|>1234 <|endoftext|>']
MOVING MASK MODEL TO GPU...DONE (0.12s)


Applying perturbations: 0it [00:00, ?it/s]
Applying perturbations: 100%|██████████| 3/3 [00:08<00:00,  2.69s/it]


MOVING BASE MODEL TO GPU...DONE (0.13s)


Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00,  6.95it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>Loris
Number of unique perturbed original texts: 1
Original text: Test <|endoftext|>Loris
Number of unique perturbed original texts: 1
Original text: <|endoftext|>1234 Loris
Number of unique perturbed original texts: 1
Original text: Test <|endoftext|>
Number of unique perturbed original texts: 1
Original text: <|endoftext|>1234 <|endoftext|>
[[0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


  0%|          | 0/42 [00:00<?, ?it/s]

texts predict proba ['<|endoftext|>123 <|endoftext|>Loris' '<|endoftext|>4 Loris'
 'Test 123 <|endoftext|>Loris' 'Test <|endoftext|>4 Loris' '<|endoftext|>'
 'Test <|endoftext|>']
MOVING MASK MODEL TO GPU...DONE (0.13s)



Applying perturbations: 0it [00:00, ?it/s]

Applying perturbations: 100%|██████████| 3/3 [00:08<00:00,  2.79s/it]


MOVING BASE MODEL TO GPU...DONE (0.12s)



Computing log likelihoods: 100%|██████████| 6/6 [00:00<00:00,  6.57it/s]


Number of unique perturbed original texts: 1
Original text: <|endoftext|>123 <|endoftext|>Loris
Number of unique perturbed original texts: 1
Original text: <|endoftext|>4 Loris
Number of unique perturbed original texts: 1
Original text: Test 123 <|endoftext|>Loris
Number of unique perturbed original texts: 1
Original text: Test <|endoftext|>4 Loris
Number of unique perturbed original texts: 1
Original text: Test <|endoftext|>
[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
shap.plots.text(shap_values)